version: '3'

tasks:
  start-build:
    description: Build and run system containers using Docker Compose.
    cmds:
      - sudo docker compose -f ./infrastructure/docker-compose.yml --env-file .env up --build
    silent: false

  start:
    description: Run system containers using Docker Compose.
    cmds:
      - sudo docker compose -f ./infrastructure/docker-compose.yml --env-file .env up
    silent: false
