version: "3.8"

volumes:
  api-db-data:


networks:
  api-network:
  nats-network:


services:
  broker-server:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    networks:
      - nats-network

  db:
    image: postgres:15.3-bullseye
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - api-db-data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: pg_isready -U ${DB_USER} -h ${DB_HOST} -p ${DB_PORT} --timeout=5
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - api-network

  # api:
  #   build:
  #     context: ../
  #     dockerfile: ./infrastructure/Dockerfile
  #   environment:
  #     - DB_HOST=${DB_HOST}
  #     - DB_USER=${DB_USER}
  #     - DB_PORT=${DB_PORT}
  #     - DB_NAME=${DB_NAME}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - BROKER_HOST=${BROKER_HOST}
  #     - BROKER_PORT=${BROKER_PORT}
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     broker-server:
  #       condition: service_started
  #   command: >
  #     bash -c "/usr/bin/psql postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT} -c 'drop database if exists ${DB_NAME}' && /usr/bin/psql postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT} -c 'create database ${DB_NAME}'"
  #   networks:
  #     - api-network
